name: Build OpenWrt

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          ca-certificates \
          clang \
          flex \
          bison \
          g++ \
          gawk \
          gcc-multilib \
          g++-multilib \
          gettext \
          git \
          libncurses5-dev \
          libssl-dev \
          python3-distutils \
          rsync \
          unzip \
          zlib1g-dev \
          file \
          wget \
          curl \
          quilt \
          nano

    - name: Set environment variables
      run: |
        echo "GCC_COLORS=error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01" >> $GITHUB_ENV

    - name: Initialize OpenWrt
      run: |
        make init

    - name: Switch to RAK7391 environment
      run: |
        # Create necessary symlinks and switch environment
        rm -f conf/files conf/patches conf/.config || true
        ln -s rak_rak7391/files conf/files
        ln -s rak_rak7391/patches conf/patches
        ln -s rak_rak7391/.config conf/.config
        cd openwrt && quilt push -a || true

    - name: Build OpenWrt
      run: |
        make -j$(nproc) V=s

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: openwrt-firmware
        path: openwrt/bin/targets/

