name: Build OpenWrt Image

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1
        with:
          submodules: 'recursive'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.0.0

      - name: Fix permissions and prepare environment
        run: |
          # 确保工作目录权限正确
          sudo chown -R $(id -u):$(id -g) .
          sudo chmod -R 755 .
          
          # 创建必要的目录并设置权限
          mkdir -p openwrt/feeds
          sudo chown -R $(id -u):$(id -g) openwrt
          
          # 配置 git 全局设置
          git config --global --add safe.directory '*'
          git config --global --add safe.directory $(pwd)
          git config --global --add safe.directory $(pwd)/openwrt

      - name: Initialize OpenWrt environment
        run: |
          docker compose run \
            --rm \
            --user $(id -u):$(id -g) \
            -e HOME=/tmp \
            -e USER_ID=$(id -u) \
            -e GROUP_ID=$(id -g) \
            chirpstack-gateway-os \
            bash -c "
              git config --global --add safe.directory '*' && \
              git config --global --add safe.directory /workdir && \
              git config --global --add safe.directory /workdir/openwrt && \
              make init
            "

      - name: Build OpenWrt image
        run: |
          docker compose run \
            --rm \
            --user $(id -u):$(id -g) \
            -e HOME=/tmp \
            -e USER_ID=$(id -u) \
            -e GROUP_ID=$(id -g) \
            chirpstack-gateway-os \
            bash -c "
              git config --global --add safe.directory '*' && \
              git config --global --add safe.directory /workdir && \
              git config --global --add safe.directory /workdir/openwrt && \
              make switch-env rak_rak7391 && \
              make -j$(nproc) V=s
            "



