name: Build OpenWrt Image

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1
        with:
          submodules: 'recursive'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.0.0

      - name: Set correct permissions
        run: |
          sudo chown -R $(id -u):$(id -g) .
          sudo chmod -R 755 .

      - name: Initialize OpenWrt environment
        run: |
          docker compose run \
            --rm \
            -e USER_ID=$(id -u) \
            -e GROUP_ID=$(id -g) \
            chirpstack-gateway-os \
            bash -c "git config --global --add safe.directory /workdir && make init"

      - name: Build OpenWrt image
        run: |
          # Create a script to run commands inside container
          cat > build.sh << 'EOF'
          #!/bin/bash
          git config --global --add safe.directory /workdir
          make switch-env rak_rak7391
          make -j$(nproc) V=s
          EOF
          chmod +x build.sh

          # Run the build script inside the container
          docker compose run \
            --rm \
            -e USER_ID=$(id -u) \
            -e GROUP_ID=$(id -g) \
            chirpstack-gateway-os \
            /bin/bash -c "./build.sh"


