name: Build OpenWrt Image

on:
  workflow_dispatch:
  push:
    branches: [main, master]

jobs:
  build-openwrt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Setup Docker
        uses: docker/setup-buildx-action@v3

      # - name: Fix directory permissions
      #   run: |
      #     sudo chown -R $USER:$USER .
      #     mkdir -p openwrt

      - name: Initialize environment
        run: |
          # docker compose build --no-cache
          # docker compose run --rm --user root chirpstack-gateway-os \
          #   chown -R buildbot:buildbot /workdir
          make init

      - name: Switch build environment
        run: |
          docker compose run --rm chirpstack-gateway-os \
            make switch-env ENV=rak_rak7391

      - name: Build OpenWrt image
        run: |
          docker compose run --rm chirpstack-gateway-os \
            make -j$(nproc) build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: openwrt-images
          path: openwrt/bin/targets/**/*
          retention-days: 5
